<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 3px solid #1890ff;
        }
        .header h1 {
            color: #1890ff;
            margin: 0;
        }
        .info-section {
            margin-bottom: 20px;
        }
        .info-label {
            font-weight: bold;
            color: #555;
        }
        .diagnosis-box {
            background-color: #f0f8ff;
            border-left: 4px solid #1890ff;
            padding: 15px;
            margin: 20px 0;
        }
        .diagnosis-box h2 {
            margin-top: 0;
            color: #1890ff;
        }
        .confidence {
            font-size: 18px;
            font-weight: bold;
            color: #28a745;
        }
        .recommendations {
            margin-top: 20px;
        }
        .recommendations li {
            margin-bottom: 10px;
        }
        .disclaimer {
            margin-top: 40px;
            padding: 15px;
            background-color: #fff3cd;
            border: 1px solid #ffc107;
            font-size: 12px;
        }
        .disclaimer strong {
            color: #dc3545;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🏥 {{ $title }}</h1>
        <p><strong>Report Date:</strong> {{ $date }} at {{ $time }}</p>
    </div>

    <div class="info-section">
        <p><span class="info-label">Patient Name:</span> {{ $patient_name }}</p>
        <p><span class="info-label">Analysis Method:</span> {{ $diagnosis['analysis_method'] ?? 'AI-Powered Analysis' }}</p>
    </div>

    <div class="diagnosis-box">
        <h2>Primary Diagnosis</h2>
        <p><strong>Condition:</strong> {{ $diagnosis['disease'] }}</p>
        <p><strong>Confidence Level:</strong> <span class="confidence">{{ number_format($diagnosis['confidence'] * 100, 1) }}%</span></p>
        <p><strong>Severity:</strong> {{ ucfirst($diagnosis['severity'] ?? 'N/A') }}</p>
        <p><strong>Description:</strong> {{ $diagnosis['description'] }}</p>
    </div>

    <div class="info-section">
        <h3>Clinical Explanation</h3>
        <p>{{ $diagnosis['explanation'] }}</p>
    </div>

    @if(isset($diagnosis['alternative_diagnoses']) && count($diagnosis['alternative_diagnoses']) > 0)
    <div class="info-section">
        <h3>Differential Diagnoses</h3>
        <ul>
            @foreach($diagnosis['alternative_diagnoses'] as $alt)
            <li>
                <strong>{{ $alt['disease'] }}</strong> - {{ number_format($alt['confidence'] * 100, 1) }}%
                <br><small>{{ $alt['description'] }}</small>
            </li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="recommendations">
        <h3>Recommendations</h3>
        <ul>
            @foreach($diagnosis['recommendations'] as $recommendation)
            <li>{{ $recommendation }}</li>
            @endforeach
        </ul>
    </div>

    <div class="disclaimer">
        <p><strong>⚠️ MEDICAL DISCLAIMER</strong></p>
        <p>
            This report is generated by an AI-powered diagnostic tool for educational and research purposes only.
            It is NOT a substitute for professional medical advice, diagnosis, or treatment.
            Always seek the advice of a qualified healthcare provider with any questions you may have regarding a medical condition.
            Never disregard professional medical advice or delay in seeking it because of information provided by this system.
        </p>
    </div>

    <div class="footer">
        <p>Heal-Io - AI-Powered Dermatological Diagnostic System</p>
        <p>For educational and research purposes only</p>
    </div>
</body>
</html>
